HandmadeStore.UI/Areas/Admin/Controllers/BrandController.cs
using HandmadeStore.Data;
using HandmadeStore.DataAccess.Repository.IRepository;
using HandmadeStore.Models;
using HandmadeStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HandmadeStore.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin+","+SD.Role_Moderator)]
    public class BrandController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BrandController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Brand> brands = _unitOfWork.Brand.GetAll();
            return View(brands);
        }

        ////Create Brand
        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        public IActionResult Create(Brand brand)
        {
            if (!string.IsNullOrEmpty(brand.Name))
            {
                var duplicatedBrand = _unitOfWork.Brand.GetFirstOrDefault(p => p.Name.ToLower() == brand.Name.ToLower());
                if (duplicatedBrand != null)
                {
                    //ModelState.AddModelError(String.Empty, "This brand name is duplicated.");
                    ModelState.AddModelError("name", "This brand name is duplicated.");
                }
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Brand.Add(brand);
                _unitOfWork.Save();
                TempData.Add("success", "Brand created successfully");
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        ////Update Brand
        //GET
        public IActionResult Update(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var brand = _unitOfWork.Brand.GetFirstOrDefault(p => p.Id == id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        //POST
        [HttpPost]
        public IActionResult Update(Brand brand)
        {
            var brandNameFromDb = _unitOfWork.Brand.GetFirstOrDefault(p => p.Id == brand.Id).Name;
            if (!string.IsNullOrEmpty(brand.Name))
            {
                var duplicatedBrand = _unitOfWork.Brand.GetFirstOrDefault(p => p.Name.ToLower() == brand.Name.ToLower());
                if (duplicatedBrand != null && duplicatedBrand.Name.ToLower() != brandNameFromDb.ToLower())
                {
                    //ModelState.AddModelError(String.Empty, "This brand name is duplicated.");
                    ModelState.AddModelError("name", "This brand name is duplicated.");
                }
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Brand.ClearChangeTracking();
                _unitOfWork.Brand.Update(brand);
                _unitOfWork.Save();
                TempData.Add("success", "Brand updated successfully");
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        ////Delete Brand
        //GET
        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var brand = _unitOfWork.Brand.GetFirstOrDefault(p => p.Id == id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int id)
        {
            var brand = _unitOfWork.Brand.GetFirstOrDefault(p => p.Id == id);
            if (brand is null)
            {
                return NotFound();
            }
            _unitOfWork.Brand.Remove(brand);
            _unitOfWork.Save();
            TempData.Add("success", "Brand deleted successfully");
            return RedirectToAction("Index");
        }
    }
}

HandmadeStore.UI/Areas/Admin/Controllers/CategoryController.cs
using HandmadeStore.Data;
using HandmadeStore.DataAccess.Repository.IRepository;
using HandmadeStore.Models;
using HandmadeStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HandmadeStore.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Moderator)]

    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> categories = _unitOfWork.Category.GetAll();
            return View(categories);
        }

        ////Create Category
        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (!string.IsNullOrEmpty(category.Name))
            {
                var duplicatedCategory = _unitOfWork.Category.GetFirstOrDefault(p => p.Name.ToLower() == category.Name.ToLower());
                if (duplicatedCategory != null)
                {
                    //ModelState.AddModelError(String.Empty, "This category name is duplicated.");
                    ModelState.AddModelError("name", "This category name is duplicated.");
                }
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                TempData.Add("success", "Category created successfully");
                return RedirectToAction("Index");
            }
            return View(category);
        }

        ////Update Category
        //GET
        public IActionResult Update(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var category = _unitOfWork.Category.GetFirstOrDefault(p => p.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        //POST
        [HttpPost]
        public IActionResult Update(Category category)
        {
            var categoryNameFromDb = _unitOfWork.Category.GetFirstOrDefault(p => p.Id == category.Id).Name;
            if (!string.IsNullOrEmpty(category.Name))
            {
                var duplicatedCategory = _unitOfWork.Category.GetFirstOrDefault(p => p.Name.ToLower() == category.Name.ToLower());
                if (duplicatedCategory != null && duplicatedCategory.Name.ToLower() != categoryNameFromDb.ToLower())
                {
                    //ModelState.AddModelError(String.Empty, "This category name is duplicated.");
                    ModelState.AddModelError("name", "This category name is duplicated.");
                }
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.ClearChangeTracking();
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                TempData.Add("success", "Category updated successfully");
                return RedirectToAction("Index");
            }
            return View(category);
        }

        ////Delete Category
        //GET
        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var category = _unitOfWork.Category.GetFirstOrDefault(p => p.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int id)
        {
            var category = _unitOfWork.Category.GetFirstOrDefault(p => p.Id == id);
            if (category is null)
            {
                return NotFound();
            }
            _unitOfWork.Category.Remove(category);
            _unitOfWork.Save();
            TempData.Add("success", "Category deleted successfully");
            return RedirectToAction("Index");
        }
    }
}

HandmadeStore.UI/Areas/Admin/Controllers/ProductController.cs
using HandmadeStore.Data;
using HandmadeStore.DataAccess.Repository.IRepository;
using HandmadeStore.Models;
using HandmadeStore.Models.Models.ViewModels;
using HandmadeStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HandmadeStore.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Moderator)]

    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _host;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment host)
        {
            _unitOfWork = unitOfWork;
            _host = host;
        }

        public IActionResult Index()
        {
            return View();
        }


        ////Upsert Product
        //GET
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(
                c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }
                ),
                BrandList = _unitOfWork.Brand.GetAll().Select(
                b => new SelectListItem
                {
                    Text = b.Name,
                    Value = b.Id.ToString()
                }
                )
            };

            if (id == null || id == 0)
            {
                //Create Product
                //ViewBag.CategoryList = CategoryList;
                //ViewData["BrandList"] = BrandList;
                return View(productVM);
            }
            else
            {
                //Update Prodect
                productVM.Product = _unitOfWork.Product.GetFirstOrDefault(p => p.Id == id);
                return View(productVM);
            }
        }

        //POST
        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string RootPath = _host.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var productsFolderPath = Path.Combine(RootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);

                    //Delete old image file if exists
                    if (productVM.Product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(RootPath, productVM.Product.ImageUrl
                            .TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(productsFolderPath,
                        fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    productVM.Product.ImageUrl = @"\images\products\" + fileName + extension;

                }
                if (productVM.Product.Id == 0)
                {
                    //Create new product
                    _unitOfWork.Product.Add(productVM.Product);
                    _unitOfWork.Save();
                    TempData["success"] = "Product created successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    //Update product
                    _unitOfWork.Product.Update(productVM.Product);
                    _unitOfWork.Save();
                    TempData["success"] = "Product updated successfully";
                    return RedirectToAction("Index");
                }

            }
            return View(productVM);
        }


        #region API Endpoints
        //Get All Products Endpoint
        [HttpGet]
        public IActionResult GetAll()
        {
            var products = _unitOfWork.Product.GetAll(includeProperties: "Category,Brand");
            return Json(new { data = products });
        }

        //Delete Product Endpoint
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var product = _unitOfWork.Product.GetFirstOrDefault(p => p.Id == id);
            if (product is null)
            {
                return Json(new { success = false, message = "Error while deleting product" });
            }
            var oldImagePath = Path.Combine(_host.WebRootPath, product.ImageUrl
                            .TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.Product.Remove(product);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Product deleted successfully" });
        }
        #endregion
    }
}

HandmadeStore.UI/Areas/Admin/Controllers/ShopController.cs
using HandmadeStore.Data;
using HandmadeStore.DataAccess.Repository.IRepository;
using HandmadeStore.Models;
using HandmadeStore.Models.Models;
using HandmadeStore.Models.Models.ViewModels;
using HandmadeStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HandmadeStore.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Moderator)]
    public class ShopController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShopController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }


        ////Upsert Product
        //GET
        public IActionResult Upsert(int? id)
        {
            Shop shop = new();

            if (id == null || id == 0)
            {
                return View(shop);
            }
            else
            {
                //Update Prodect
                shop = _unitOfWork.Shop.GetFirstOrDefault(p => p.Id == id);
                return View(shop);
            }
        }

        //POST
        [HttpPost]
        public IActionResult Upsert(Shop shop)
        {
            if (ModelState.IsValid)
            {
                if (shop.Id == 0)
                {
                    //Create new product
                    _unitOfWork.Shop.Add(shop);
                    _unitOfWork.Save();
                    TempData["success"] = "shop created successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    //Update product
                    _unitOfWork.Shop.Update(shop);
                    _unitOfWork.Save();
                    TempData["success"] = "shop updated successfully";
                    return RedirectToAction("Index");
                }

            }
            return View(shop);
        }


        #region API Endpoints
        //Get All Products Endpoint
        [HttpGet]
        public IActionResult GetAll()
        {
            var shops = _unitOfWork.Shop.GetAll();
            return Json(new { data = shops });
        }

        //Delete Product Endpoint
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var shop = _unitOfWork.Shop.GetFirstOrDefault(p => p.Id == id);
            if (shop is null)
            {
                return Json(new { success = false, message = "Error while deleting product" });
            }
         
            _unitOfWork.Shop.Remove(shop);
            _unitOfWork.Save();
            return Json(new { success = true, message = "shop deleted successfully" });
        }
        #endregion
    }
}

HandmadeStore.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http.Extensions
@inject IHttpContextAccessor HttpContextAccessor
@inject IViewLocalizer localizer
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var culture = requestCulture.RequestCulture.Culture.Name;
    var isArabic = culture == "ar-EG";
}

<!DOCTYPE html>
<html lang="@(isArabic?"ar":"eg")">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HandmadeStore.UI</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HandmadeStore.UI.styles.css" asp-append-version="true" />
    @if (isArabic)
    {
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="~/css/rtl.css" />
    }
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary mb-2">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" width="130" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="Index">@localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="About">@localizer["About"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="Contact">@localizer["Contact"]</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {


                            if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Moderator))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-light dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        @localizer["Admin Panel"]
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">@localizer["Categories"]</a></li>
                                        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Brand" asp-action="Index">@localizer["Brands"]</a></li>
                                        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Shop" asp-action="Index">@localizer["Shops"]</a></li>
                                        <li><a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">@localizer["Products"]</a></li>
                                        <li class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" asp-area="Identity" asp-action="/Account/Register">@localizer["Create User"]</a></li>


                                    </ul>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @await Component.InvokeAsync("Cart")
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Order" asp-action="Index">@localizer["Manage Orders"]</a>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        @if (!isArabic)
                        {
                            <li class="nav-item"><a class="nav-link text-light" href="/Customer/Home/SetCulture?lang=ar-EG&returnUrl=@Context.Request.GetEncodedPathAndQuery()">العربية</a></li>
                        }
                        else
                        {
                            <li class="nav-item"><a class="nav-link text-light" href="/Customer/Home/SetCulture?lang=en-US&returnUrl=@Context.Request.GetEncodedPathAndQuery()">English</a></li>
                        }
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="p-2">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-center text-light bg-primary">
        <div class="container">
            @localizer["&copy; Handmade Store - 2022"]
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/2i7pnlj46cgmoyt61hldeumjioqio6h6gqgqbyvq2ek04fpb/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/SignalrClients/Reviews.js"></script>
    <script src="~/js/SignalrClients/Message.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HandmadeStore.UI/Views/Shared/_Notification.cshtml
@{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    if (TempData["success"] != null)
    {
        <script type="text/javascript">
            toastr.success('@TempData["success"]', 'Homemade Store', { timeOut: 2000 })
        </script>
    }
}

HandmadeStore.UI/Views/Shared/_Review.cshtml
@using HandmadeStore.Models.Models

@model Review



<div class="card">
    <form method="post">
        <div class="text-center my-2">
            <textarea asp-for="ReviewText" class="w-75"></textarea>
            <button asp-action="addReview" type="submit" class="btn btn-info w-50">Add Review</button>
        </div>
    </form>   
    <partial name="_Reviews"></partial>
</div>

HandmadeStore.UI/Views/Shared/_Reviews.cshtml
@using HandmadeStore.Models.Models
@using System.Globalization

@foreach (var item in TempData["Reviews"] as IEnumerable<Review>)
{
    <div>
        <div class="row d-flex ">
            <div class="d-flex flex-column">
                <h4 class="ms-2 mb-0">@item.ApplicationUser.Name</h4>
            </div>
            <div class="ml-auto">
                <p class="text-muted ms-2 mb-0">
                    @item.ReviewDate.Value.ToString("f",CultureInfo.CreateSpecificCulture("en-US"))
                </p>
            </div>
            <div class="row text-left">
                <h5 class="ms-4 mt-1">@item.ReviewText</h5>
            </div>
            <div>
                <hr />
            </div>
        </div>
    </div>
}